---
- name: Install & Uninstall
  hosts: localhost
  gather_facts: true
  pre_tasks:
    - name: Include pre-tasks
      ansible.builtin.import_tasks: tasks/pre.yml
      tags: always

  roles:
    - role: common

    # - role: slack

    - role: oh_my_zsh

    - role: nix

    # - role: awscli
    #   become: true

    # - role: nvm

    # - role: pyenv

    # - role: kubectl
    #   become: true

    # - role: podman_compose

    # - role: awscdk

    # - role: helm
    #   become: true

    # - role: tfenv

    # - role: terragrunt

    - role: visual_studio_code
      vars:
        visual_studio_code_version: ''
        visual_studio_code_build: stable
        visual_studio_code_mirror: 'https://packages.microsoft.com'
        visual_studio_code_gpgcheck: true
        users:
          - username: 'ansible'
            visual_studio_code_extensions:
              - redhat.ansible
              - 4ops.terraform
              - fredwangwang.vscode-hcl-format
              - golang.go
              - hashicorp.hcl
              - hashicorp.terraform
              - visualstudioexptteam.vscodeintellicode
              - shakram02.bash-beautify
              - ms-azuretools.vscode-docker
              - k--kato.intellij-idea-keybindings
              - ms-kubernetes-tools.vscode-kubernetes-tools
              - ms-python.python
              - redhat.vscode-yaml
              - formulahendry.code-runner
              - jetmartin.bats
      tags:
        - vscode_install
        - install
