---
- name: Install & Uninstall
  hosts: localhost
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    # priority
    - role: oh_my_zsh

    # - role: awscdk

    # - role: nvm

    # any order
    - role: nix

    # - role: awscli
    #   become: true

    # - role: kubectl
    #   become: true

    # - role: helm
    #   become: true

    # - role: terragrunt

    # - role: tfenv

    # - role: podman_compose

    # - role: pyenv

    - role: vscode_uninstall

    - role: slack

    - role: common
