---
- name: Install Terragrunt
  block:
    - name: Check if Terragrunt is installed
      ansible.builtin.stat:
        path: "{{ dest_path }}"
      register: tg_is_installed

    - name: Download Terragrunt
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: "{{ dest_path }}"
      when: tg_is_installed.stat.exists == False

    - name: Ensure the Terragrunt file is executable
      ansible.builtin.file:
        path: "{{ dest_path }}"
        mode: "0755"
      when: not tg_is_installed.stat.exists

    - name: Terragrunt version
      ansible.builtin.command:
        cmd: "{{ zsh_shell_cmd }} 'terragrunt --version'"
