---
- name: Install Terragrunt
  block:
    - name: Check if Terragrunt is installed
      ansible.builtin.stat:
        path: "{{ terragrunt_dest_path }}"
      register: tg_is_installed

    - name: Download Terragrunt
      ansible.builtin.get_url:
        url: "{{ terragrunt_download_url }}"
        dest: "{{ terragrunt_dest_path }}"
        mode: "0755"
      when: not tg_is_installed.stat.exists

    - name: Check Terragrunt version
      ansible.builtin.command:
        cmd: "{{ zsh_shell_cmd }} 'terragrunt --version'"
      register: terragrunt_version
      changed_when: false

    - name: Display Terragrunt version
      ansible.builtin.debug:
        msg: "Terragrunt version: {{ terragrunt_version.stdout }}"
