
- block:
    - name: Terragrunt installation tasks
      include_tasks: install.yml
  tags:
    - terragrunt_install
    - install

- block:
    - name: Terragrunt uninstallation tasks
      include_tasks: uninstall.yml
  tags:
    - terragrunt_uninstall
    - uninstall
