---
- name: Uninstall Terragrunt
  block:
    - name: Remove files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ terragrunt_dest_path }}"
