---
- name: Install ZSH & OMZ
  ansible.builtin.include_tasks: install.yml
  tags:
    - omz_install
    - install

- name: Uninstall ZSH & OMZ
  ansible.builtin.include_tasks: uninstall.yml
  tags:
    - omz_uninstall
    - uninstall
