version: '3'
services:
  ansible:
    build:
      context: .
      dockerfile: docker/Dockerfile.ansible
      args:
        - USER=ansible
    container_name: "ansible"
    command: "sleep infinity"
    user: "1000:1000"
    x-podman:
      uidmaps:
        - 1000:0:1
        - 0:1:1000
    depends_on:
      - playground
    volumes:
      - "$PWD/:/home/ansible/playbook:Z"
      - $PWD/docker/config:/etc/ansible:Z
      - $PWD/docker/keys/ansible:/home/ansible/.ssh/id_rsa:Z,ro

  playground:
    build:
      context: .
      dockerfile: docker/Dockerfile.dest
      args:
        - USER=ansible
    ports:
      - 8000:80
    volumes:
      - "$PWD/docker/keys/ansible.pub:/home/ansible/.ssh/authorized_keys:ro,Z"
