---
- name: Validate ZSH zsh_cmd parameter
  assert:
    that:
      - "'{{ zsh_cmd }}' is defined"
      - "'{{ zsh_cmd }}' | length > 0"
    fail_msg: "The zsh_cmd parameter is not defined or is empty"

- name: run ZSH cmd
  ansible.builtin.shell:
    cmd: "{{ zsh_shell_cmd }} '{{ zsh_cmd }}'"
