---
- name: Check if Kubetl is installed
  ansible.builtin.stat:
    path: "{{ kubectl_bin_directory }}/kubectl"
  register: kubectl_installed

- name: Install Kubectl
  when: not kubectl_installed.stat.exists
  block:
    - name: Download kubectl binary
      ansible.builtin.get_url:
        url: https://cdn.dl.k8s.io/release/v{{ kubectl_version }}/bin/{{ kubectl_os }}/{{ kubectl_arch }}/kubectl
        checksum: "{{ kubectl_checksum_binary }}"
        dest: "{{ kubectl_tmp_directory }}"
        mode: "0600"

    - name: Copy kubectl binary to destination directory
      ansible.builtin.copy:
        src: "{{ kubectl_tmp_directory }}/{{ item }}"
        dest: "{{ kubectl_bin_directory }}/{{ item }}"
        mode: "{{ kubectl_binary_mode }}"
        owner: "{{ kubectl_owner }}"
        group: "{{ kubectl_group }}"
        remote_src: true
      with_items:
        - kubectl

    - name: Kubectl version
      ansible.builtin.command: kubectl version --client
      register: get_kubectl_version_output
      changed_when: get_kubectl_version_output.rc != 0
