---
- name: Uninstall kubectl
  tags:
    - uninstall
  block:
    - name: Remove kubectl
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ kubectl_bin_directory }}/kubectl"
        - "{{ user_home }}/.kube"
