---
- name: Install AWS CDK
  block:
    - name: Install typescript
      ansible.builtin.command: "{{ zsh_shell_cmd }} 'npm i -g typescript'"
    - name: Install AWS CDK
      ansible.builtin.command: "{{ zsh_shell_cmd }} 'npm i -g aws-cdk'"
    - name: Version
      ansible.builtin.command: "{{ zsh_shell_cmd }} 'cdk --version'"
