- block:
    - name: AWS CDK installation tasks
      include_tasks: install.yml
  tags:
    - awscdk_install
    - install

- block:
    - name: AWS CDK uninstallation tasks
      include_tasks: uninstall.yml
  tags:
    - awscdk_uninstall
    - uninstall
