---
- name: Remove VSCode files
  block:
    - name: Remove code
      become: true
      ansible.builtin.package:
        name: code
        state: absent

    - name: Remove extensions
      ansible.builtin.file:
        path: "{{ user_home }}/{{ item }}"
        state: absent
        force: true
      with_items:
        - .vscode
        - .config/Code

    - name: Remove usr/share/code
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
        force: true
      with_items:
        - /usr/share/code/

    - name: Remove specific YUM repository
      become: true
      ansible.builtin.yum_repository:
        name: code
        state: absent

    - name: Remove yum repo file
      become: true
      ansible.builtin.file:
        path: /etc/yum.repos.d/vscode.repo
        state: absent

    - name: Update the YUM package list
      become: true
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: true
        update_only: true
