FROM fedora

ARG USER
ENV HOME=/home/$USER

RUN dnf update -y && dnf install sudo openssh-server python3 python3-pip inotify-tools -y && \
    mkdir -p /run/sshd && \
    groupadd -g 1000 ansible && \
    useradd -u 1000 -g ansible -m -s /bin/bash $USER && \
    echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER && \
    ssh-keygen -A && \
    pip install packaging setuptools

WORKDIR $HOME

CMD [ "/usr/sbin/sshd", "-D", "-e" ]
