FROM fedora:40

ARG USER
ARG UID
ENV HOME=/home/$USER

RUN dnf update -y && dnf install sudo git openssh-server python3 python3-pip inotify-tools -y && \
    mkdir -p /run/sshd && \
    groupadd -g ${UID} ${USER} && \
    useradd -u ${UID} -g ${USER} -m -s /bin/bash $USER && \
    echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER && \
    ssh-keygen -A && \
    pip install packaging setuptools

WORKDIR $HOME

CMD [ "/usr/sbin/sshd", "-D", "-e" ]
