
- name: Install Podman Compose
  block:
    - name: install via cURL
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: "{{ user_home }}/{{ dest_path }}"
        mode: '0755'

    - name: version
      ansible.builtin.shell:
        cmd: "{{ zsh_shell_cmd }} 'podman-compose -v'"
