---
common_packages:
  - "@Development Tools"
  - openssl
  - openssl-devel
  - zlib-devel
  - bzip2
  - bzip2-devel
  - readline-devel
  - sqlite
  - sqlite-devel
  - zip
  - unzip
  - vlc
  - curl
  - wget
  - telnet
  - git
  - xz
  - tar

common_pip_packages:
