---
packages:
  - git
  - openssl
  - openssl-devel
  - zlib-devel
  - bzip2
  - bzip2-devel
  - readline-devel
  - sqlite
  - sqlite-devel
  - zip
  - unzip
  - podman

pip_packages:
  - pyyaml
  - python-dotenv
