---
- name: Check if Helm is installed
  ansible.builtin.stat:
    path: /usr/local/bin/helm
  register: helm_installed

- name: Install Helm
  when: helm_installed.stat.exists == False
  block:
    - name: Download script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: "{{ helm_tmp_directory }}/get_helm.sh"
        mode: "0700"

    - name: Install
      ansible.builtin.command:
        cmd: sh {{ helm_tmp_directory }}/get_helm.sh
      environment:
        DESIRED_VERSION: "{{ helm_version | default('') }}"

    - name: Version
      ansible.builtin.command: helm version
