---
- name: Prepare environment
  tags:
    - install
  block:
    - name: Create .local/bin dir
      ansible.builtin.file:
        path: "{{ local_bin_dir }}"
        state: directory
        mode: "0755"
