---
- name: Install common packages
  tags:
    - install
  block:
    - name: Install one-time packages
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items: "{{ common_persistent_packages }}"

    - name: Install app deps packages
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items: "{{ common_packages }}"

    - name: Ensure setuptools and packaging are installed using command
      ansible.builtin.command: python3 -m pip install --upgrade packaging
      register: install_req_pip_tools_output
      changed_when: install_req_pip_tools_output.rc != 0

    - name: Pip packages
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      with_items: "{{ common_pip_packages }}"
