---
- block:
    - name: Checks
      ansible.builtin.include_tasks: checks.yml
- tags:
    - common_install
    - install

  block:
    - name: Common installation tasks
      ansible.builtin.include_tasks: install.yml
- tags:
    - prepare_env
    - install

  block:
    - name: Prepare env
      ansible.builtin.include_tasks: environment.yml
- tags:
    - common_uninstall
    - uninstall
  block:
    - name: Common uninstallation tasks
      ansible.builtin.include_tasks: uninstall.yml
