---
- name: Prepare env
  ansible.builtin.include_tasks: environment.yml
  tags:
    - prepare_env
    - install

- name: Common installation tasks
  ansible.builtin.include_tasks: install.yml
  tags:
    - common_install
    - install

- name: Common uninstallation tasks
  ansible.builtin.include_tasks: uninstall.yml
  tags:
    - common_uninstall
    - uninstall
