
- block:
    - name: Checks
      include_tasks: checks.yml

- block:
    - name: Common installation tasks
      include_tasks: install.yml
  tags:
    - common_install
    - install

- block:
    - name: Prepare env
      include_tasks: environment.yml
  tags:
    - prepare_env
    - install

- block:
    - name: Common uninstallation tasks
      include_tasks: uninstall.yml
  tags:
    - common_uninstall
    - uninstall
