---
- name: Uninstall common packages
  block:
    - name: Pip packages
      ansible.builtin.pip:
        name: "{{ item }}"
        state: absent
      with_items: "{{ pip_packages }}"

    - name: Remove files
      ansible.builtin.file:
        path: "{{ user_home }}/{{ item }}"
        state: absent
        force: true
      with_items:
        - .cache/pip
        - "{{ local_bin_dir }}"

    - name: Via package manager
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      with_items: "{{ packages }}"

    # - name: delete pip packaging
    #   ansible.builtin.command: python3 -m pip uninstall -y packaging

    - name: Delete dev tools
      become: true
      ansible.builtin.command: yum groupremove "Development Tools" -y
      register: delete_dev_pkgs_output
      changed_when: delete_dev_pkgs_output.rc != 0
