---
- name: Uninstall common packages
  block:
    - name: Pip packages
      ansible.builtin.pip:
        name: "{{ item }}"
        state: absent
      with_items: "{{ common_pip_packages }}"

    - name: Remove files
      ansible.builtin.file:
        path: "{{ user_home }}/{{ item }}"
        state: absent
        force: true
      with_items:
        - .cache/pip
        - "{{ local_bin_dir }}"

    - name: Via package manager
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      with_items: "{{ common_packages }}"

    # - name: delete pip packaging
    #   ansible.builtin.command: python3 -m pip uninstall -y packaging
