---
- name: Install NVM & NodeJS
  ansible.builtin.include_tasks: install.yml
  tags:
    - nvm_install
    - install

- name: Uninstall NVM & NodeJS
  ansible.builtin.include_tasks: uninstall.yml
  tags:
    - nvm_uninstall
    - uninstall
