---
- tags:
    - nvm_install
    - install

  block:
    - name: Install NVM & NodeJS
      ansible.builtin.include_tasks: install.yml
- tags:
    - nvm_uninstall
    - uninstall
  block:
    - name: Uninstall NVM & NodeJS
      ansible.builtin.include_tasks: uninstall.yml
