---
- name: Nix installation tasks
  when: is_selinux_enabled
  ansible.builtin.include_tasks: install.yml
  tags:
    - nix_install
    - install

- name: Nix uninstallation tasks
  when: is_selinux_enabled
  ansible.builtin.include_tasks: uninstall.yml
  tags:
    - nix_uninstall
    - uninstall
