name: Test Ansible install playbook

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

env:
  USER_CNT_NAME: "ansible"

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dest image
        run: docker build -t playbook_playground --build-arg USER=$USER_CNT_NAME -f docker/Dockerfile.dest .

      # - name: Build source image
      #   run: docker build -t playbook_ansible --build-arg USER=$USER_CNT_NAME -f docker/Dockerfile.ansible .

      - name: Run dest
        run: docker run -d --name playground -p 8000:80 -u root playbook_playground

      - name: Run command in Docker container
        run: docker exec playground bash -c "echo 'Hello from inside the container!'"
