name: Test Ansible install playbook

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

env:
  USER_CNT_NAME: "ansible"

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dest image
        run: docker build -t playbook_playground --build-arg USER=$USER_CNT_NAME -f docker/Dockerfile.dest .

      - name: Build source image
        run: docker build -t playbook_ansible --build-arg USER=$USER_CNT_NAME -f docker/Dockerfile.ansible .

      - name: Run dest
        run: docker run -d --name playground playbook_playground

      - name: Run source
        run: |
          docker run \
            --rm \
            -d \
            -v ./:/home/ansible/playbook:Z \
            -v ./docker/config/ansible.cfg:/etc/ansible/ansible.cfg:Z \
            -v ./docker/config/ssh_config:/home/$USER_CNT_NAME/.ssh/config:Z,ro \
            -v ./docker/keys/ansible:/home/$USER_CNT_NAME/.ssh/id_rsa:Z,ro \
            --name ansible \
            playbook_ansible sleep infinity

      - name: Run install playbook
        run: docker exec ansible bash -c "./scripts/install.sh"
