name: Tests checks

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

env:
  USER_CNT_NAME: "ansible"
  NET_NAME: "ansible_bridge"
  HOME_DIR: "/home/ansible"

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate kp
        run: ssh-keygen -t rsa -b 4096 -C "ansible" -f ./docker/keys/id_rsa -N ""

      - name: Build playground image
        run: |
          docker build \
            -t playbook_playground \
            --build-arg USER=$USER_CNT_NAME \
            --build-arg UID=$UID \
            -f docker/Dockerfile.dest \
            .

      - name: Build ansible image
        run: |
          docker build \
            -t playbook_ansible \
            --build-arg USER=$USER_CNT_NAME \
            --build-arg UID=$UID \
            -f docker/Dockerfile.ansible \
            .

      - name: Create docker network
        run: docker network create $NET_NAME

      - name: Run playground
        run: |
          docker run \
            -d \
            --network $NET_NAME \
            --network-alias playground \
            -v ./docker/keys/id_rsa.pub:$HOME_DIR/.ssh/authorized_keys:Z \
            --name playground \
            playbook_playground

      - name: Run ansible
        run: |
          docker run \
            --rm \
            -d \
            --name ansible \
            -v ./playbook/:$HOME_DIR/playbook/:Z,ro \
            -v ./scripts/:$HOME_DIR/scripts/:Z,ro \
            -v ./docker/config/ssh_client_config:$HOME_DIR/.ssh/config:Z,ro \
            -v ./docker/keys/id_rsa:$HOME_DIR/.ssh/id_rsa:Z \
            --network $NET_NAME --network-alias ansible \
            playbook_ansible sleep infinity

      - name: Verify ssh connection
        run: |
          # docker exec -u root ansible bash -c "ls -lah ~/.ssh"
          # docker exec -u root ansible bash -c "chown ansible:ansible /home/ansible/.ssh/id_rsa"
          # docker exec -u root playground bash -c "chown ansible:ansible /home/ansible/.ssh/authorized_keys"
          # docker exec ansible bash -c "ssh-keyscan -H $(sed -n 2p playbook/hosts/docker) >> ~/.ssh/known_hosts"
          docker exec ansible bash -c "ssh -vvv ansible@playground -- 'whoami'"
 
      - name: Run install playbook
        run: docker exec ansible bash -c "./scripts/install.sh"

      - name: Run uninstall playbook
        run: docker exec ansible bash -c "./scripts/uninstall.sh"
