name: Ansible tests

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

env:
  USER_CNT_NAME: "ansible"
  NET_NAME: "ansible_bridge"
  HOME_DIR: "/home/ansible"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          working_directory: playbook

  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: whoami ga
        run: whoami

      - name: prepare
        run: |
          ssh-keygen -t rsa -b 4096 -C "ansible" -f ./docker/keys/ansible -N ""
          chmod 600 ./docker/config/ssh_config

      - name: Build dest image
        run: |
          docker build \
            -t playbook_playground \
            --build-arg USER=$USER_CNT_NAME \
            -f docker/Dockerfile.dest \
            .

      - name: Build source image
        run: |
          docker build \
            -t playbook_ansible \
            --build-arg USER=$USER_CNT_NAME \
            -f docker/Dockerfile.ansible \
            .

      - name: create docker network
        run: docker network create $NET_NAME

      - name: Run dest
        run: |
          docker run \
            -d \
            --network $NET_NAME \
            --network-alias playground \
            -v ./docker/config/sshd_config:/etc/ssh/sshd_config:Z,ro \
            -v ./docker/keys/ansible.pub:$HOME_DIR/.ssh/authorized_keys:Z,ro \
            --name playground \
            playbook_playground

      - name: Run source
        run: |
          docker run \
            --rm \
            -d \
            --name ansible \
            -v ./docker/config/ansible.cfg:/etc/ansible/ansible.cfg:ro \
            -v ./playbook/:$HOME_DIR/playbook/:Z,ro \
            -v ./scripts/:$HOME_DIR/scripts/:Z,ro \
            -v ./docker/config/ssh_config:$HOME_DIR/.ssh/config:Z,ro \
            -v ./docker/keys/ansible:$HOME_DIR/.ssh/id_rsa:Z,ro \
            --network $NET_NAME --network-alias ansible \
            playbook_ansible sleep infinity

      - name: check ssh connection
        run: docker exec ansible bash -c "ssh ansible@playground -- 'whoami'"

      - name: Run install playbook
        run: docker exec ansible bash -c "./scripts/install.sh"

      - name: Run uninstall playbook
        run: docker exec ansible bash -c "./scripts/uninstall.sh"
