---
- name: Install Podman Compose
  tags:
    - install
  block:
    - name: Install via cURL
      ansible.builtin.get_url:
        url: "{{ podman_compose_download_url }}"
        dest: "{{ podman_compose_dest_path }}"
        mode: "0755"

    - name: Version
      ansible.builtin.command:
        cmd: "{{ zsh_shell_cmd }} 'podman-compose -v'"
      register: get_podman_version_output
      changed_when: get_podman_version_output.rc != 0
